InventoryStudio/InventoryStudio/Models/Company/CreateCompanyViewModel.cs
using System.ComponentModel;
using Microsoft.AspNetCore.Components.Web;

namespace InventoryStudio.Models.Company
{
    public class CreateCompanyViewModel
    {
        [DisplayName("Company Name")] public string CompanyName { get; set; }

        [DisplayName("Automate Fulfillment")] public bool AutomateFulfillment { get; set; }

        [DisplayName("Shippo API Key")] public string ShippoAPIKey { get; set; }

        [DisplayName("Include Packing Slip On Label")]
        public bool IncludePackingSlipOnLabel { get; set; }

        [DisplayName("Default Fulfillment Method")]
        public string DefaultFulfillmentMethod { get; set; }

        [DisplayName("Default Fulfillment Strategy")]
        public string DefaultFulfillmentStrategy { get; set; }

        [DisplayName("Default Allocation Strategy")]
        public string DefaultAllocationStrategy { get; set; }
    }
}

InventoryStudio/InventoryStudio/Models/Company/EditCompanyViewModel.cs
using System.ComponentModel;

namespace InventoryStudio.Models.Company
{
    public class EditCompanyViewModel
    {
        public string CompanyID { get; set; }

        [DisplayName("Company Name")] public string CompanyName { get; set; }

        [DisplayName("Automate Fulfillment")] public bool AutomateFulfillment { get; set; }

        [DisplayName("Shippo API Key")] public string ShippoAPIKey { get; set; }

        [DisplayName("Include Packing Slip On Label")]
        public bool IncludePackingSlipOnLabel { get; set; }

        [DisplayName("Default Fulfillment Method")]
        public string DefaultFulfillmentMethod { get; set; }

        [DisplayName("Default Fulfillment Strategy")]
        public string DefaultFulfillmentStrategy { get; set; }

        [DisplayName("Default Allocation Strategy")]
        public string DefaultAllocationStrategy { get; set; }
    }
}

InventoryStudio/InventoryStudio/Controllers/CompanyController.cs
using InventoryStudio.Data;
using InventoryStudio.Models;
using InventoryStudio.Models.Company;
using ISLibrary;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using System.Text.Json;
using Syncfusion.EJ2.Base;

namespace InventoryStudio.Controllers
{
    public class CompanyController : BaseController
    {
        private readonly UserManager<User> _userManager;
        private readonly ApplicationDbContext _context;

        public CompanyController(UserManager<User> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (string.IsNullOrEmpty(userId))
                return Redirect("/Identity/Account/Login");
            var user = await _userManager.GetUserAsync(User);
            List<Company> companies = user.AspNetUser.Companies;
            return View(companies);
        }

        public async Task<IActionResult> Create()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (string.IsNullOrEmpty(userId))
            {
                return Redirect("/Identity/Account/Login");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user.UserType.Equals("Normal"))
            {
                var filter = new CompanyFilter();
                filter.CreatedBy = new CLRFramework.Database.Filter.StringSearch.SearchFilter();
                filter.CreatedBy.SearchString = userId;
                var companies = Company.GetCompanies(filter);
                if (companies.Count > 0)
                {
                    ViewBag.ErrorMessage = "Normal users can only create one company";
                    return View("Error");
                }
            }

            CreateCompanyViewModel viewModel = new CreateCompanyViewModel();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCompanyViewModel input)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId);
            Company parentCompany = null;
            if (user.UserType.Equals("3PL"))
            {
                var filter = new CompanyFilter();
                filter.CreatedBy = new CLRFramework.Database.Filter.StringSearch.SearchFilter();
                filter.CreatedBy.SearchString = userId;
                filter.ParentCompanyID = new CLRFramework.Database.Filter.StringSearch.SearchFilter();
                filter.ParentCompanyID.Operator = CLRFramework.Database.Filter.StringSearch.SearchOperator.empty;
                var companies = Company.GetCompanies(filter);
                if (companies.Count > 0)
                    parentCompany = companies[0];
            }

            if (string.IsNullOrEmpty(userId))
                return Redirect("/Identity/Account/Login");
            if (ModelState.IsValid)
            {
                Company company = new Company();
                company.CompanyName = input.CompanyName;
                company.AutomateFulfillment = input.AutomateFulfillment;
                company.ShippoAPIKey = input.ShippoAPIKey;
                company.IncludePackingSlipOnLabel = input.IncludePackingSlipOnLabel;
                company.DefaultFulfillmentMethod = input.DefaultFulfillmentMethod;
                company.DefaultFulfillmentStrategy = input.DefaultFulfillmentStrategy;
                company.DefaultAllocationStrategy = input.DefaultAllocationStrategy;
                company.CompanyGUID = Guid.NewGuid().ToString();
                if (parentCompany != null)
                    company.ParentCompanyID = parentCompany.CompanyID;
                company.CreatedOn = DateTime.Now;
                company.CreatedBy = Convert.ToInt32(userId);
                company.Create();
                AspNetUserCompany aspNetUserCompany = new AspNetUserCompany();
                aspNetUserCompany.UserId = userId;
                aspNetUserCompany.CompanyID = company.CompanyID;
                aspNetUserCompany.Create();

                var existingOrganizationClaim = _context.UserClaims
                    .FirstOrDefault(c => c.UserId == Convert.ToInt32(userId) && c.ClaimType == "CompanyId");

                if (existingOrganizationClaim != null)
                {
                    existingOrganizationClaim.ClaimValue = company.CompanyID;
                    _context.UserClaims.Update(existingOrganizationClaim);
                }
                else
                {
                    var newOrganizationClaim = new IdentityUserClaim<int>
                    {
                        UserId = Convert.ToInt32(userId),
                        ClaimType = "CompanyId",
                        ClaimValue = company.CompanyID
                    };
                    _context.UserClaims.Add(newOrganizationClaim);
                }

                return RedirectToAction("SelectCompany", "Account");
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
                return NotFound();
            var company = new Company(id);
            if (company == null)
                return NotFound();
            var editViewModel = new EditCompanyViewModel();
            editViewModel.CompanyID = company.CompanyID;
            editViewModel.CompanyName = company.CompanyName;
            editViewModel.AutomateFulfillment = company.AutomateFulfillment;
            editViewModel.ShippoAPIKey = company.ShippoAPIKey;
            editViewModel.IncludePackingSlipOnLabel = company.IncludePackingSlipOnLabel;
            editViewModel.DefaultFulfillmentMethod = company.DefaultFulfillmentMethod;
            editViewModel.DefaultFulfillmentStrategy = company.DefaultFulfillmentStrategy;
            editViewModel.DefaultAllocationStrategy = company.DefaultAllocationStrategy;
            return View(editViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, EditCompanyViewModel input)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (string.IsNullOrEmpty(userId))
                return Redirect("/Identity/Account/Login");

            if (string.IsNullOrEmpty(id))
                return NotFound();

            var company = new Company(id);
            if (company == null)
                return NotFound();

            company.CompanyName = input.CompanyName;
            company.AutomateFulfillment = input.AutomateFulfillment;
            company.ShippoAPIKey = input.ShippoAPIKey;
            company.DefaultFulfillmentMethod = input.DefaultFulfillmentMethod;
            company.DefaultFulfillmentStrategy = input.DefaultFulfillmentStrategy;
            company.DefaultAllocationStrategy = input.DefaultAllocationStrategy;
            company.IncludePackingSlipOnLabel = input.IncludePackingSlipOnLabel;
            company.UpdatedBy = Convert.ToInt32(userId);
            company.Update();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
                return NotFound();
            var company = new Company(id);
            if (company == null)
                return NotFound();
            return View(company);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (string.IsNullOrEmpty(id))
                return NotFound();
            var company = new Company(id);
            if (company == null)
                return NotFound();
            company.Delete();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(string id)
        {
            if (string.IsNullOrEmpty(id))
                return NotFound();
            var company = new Company(id);
            if (company == null)
                return NotFound();
            return View(company);
        }

        public IActionResult Insert([FromBody] CRUDModel<AspNetUsers> value)
        {
            return Json(value.Value);
        }

        public IActionResult Update([FromBody] CRUDModel<AspNetUsers> value)
        {
            return Json(value.Value ?? new AspNetUsers());
        }

        public IActionResult Remove([FromBody] CRUDModel<AspNetUsers> value)
        {
            if (value.Key != null)
            {
            }

            return Json(value);
        }

        public IActionResult UrlDataSource([FromBody] DataManagerRequest dm)
        {
            IEnumerable<Company> dataSource = new List<Company>().AsEnumerable();
            DataOperations operation = new();
            int totalRecord = 0;
            if (dm.Skip != 0 || dm.Take != 0)
            {
                Claim? company = User.Claims.FirstOrDefault(t => t.Type == "CompanyId");
                if (company != null)
                {
                    CompanyFilter companyFilter = new();
                    dataSource = Company.GetCompanies(
                        companyFilter,
                        dm.Take,
                        (dm.Skip / dm.Take) + 1,
                        out totalRecord
                    );
                }
            }

            if (dm.Search != null && dm.Search.Count > 0)
            {
                dataSource = operation.PerformSearching(dataSource, dm.Search); //Search
            }

InventoryStudio/InventoryStudio/Views/Company/Create.cshtml
@model InventoryStudio.Models.Company.CreateCompanyViewModel

@{
    ViewData["Title"] = "Company-Create";
}


<div class="container-fluid py-4">
    <div class="card custom-card">
        <div class="card-header hstack justify-content-between align-items-center">
            <div class="card-title">Create Company</div>
            <a asp-controller="Company" asp-action="Index" class="btn btn-sm btn-light">Back to List</a>
        </div>
        <div class="card-body">
            <form class="row" asp-controller="Company" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group col-md-6 mb-3">
                    <label asp-for="CompanyName" class="form-label"></label>
                    <input asp-for="CompanyName" class="form-control"/>
                    <span asp-validation-for="CompanyName" class="text-danger"></span>
                </div>

                <div class="form-group col-md-6 mb-3">
                    <label asp-for="ShippoAPIKey" class="form-label"></label>
                    <input asp-for="ShippoAPIKey" class="form-control"/>
                    <span asp-validation-for="ShippoAPIKey" class="text-danger"></span>
                </div>

                <div class="form-group col-md-6 mb-3">
                    <label asp-for="DefaultFulfillmentMethod" class="form-label"></label>
                    <input asp-for="DefaultFulfillmentMethod" class="form-control"/>
                    <span asp-validation-for="DefaultFulfillmentMethod" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6 mb-3">
                    <label asp-for="DefaultFulfillmentStrategy" class="form-label"></label>
                    <input asp-for="DefaultFulfillmentStrategy" class="form-control"/>
                    <span asp-validation-for="DefaultFulfillmentStrategy" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6 mb-3">
                    <label asp-for="DefaultAllocationStrategy" class="form-label"></label>
                    <input asp-for="DefaultAllocationStrategy" class="form-control"/>
                    <span asp-validation-for="DefaultAllocationStrategy" class="text-danger"></span>
                </div>
                <div class="form-group form-check col-md-12 mb-3 ms-3">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="AutomateFulfillment"/> @Html.DisplayNameFor(model => model.AutomateFulfillment)
                    </label>
                </div>
                <div class="form-group form-check col-md-12 mb-3 ms-3">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="IncludePackingSlipOnLabel"/> @Html.DisplayNameFor(model => model.IncludePackingSlipOnLabel)
                    </label>
                </div>
                <div class="form-group col-md-12">
                    <input type="submit" value="Save" class="btn btn-primary"/>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

InventoryStudio/InventoryStudio/Views/Company/Delete.cshtml
@model Company

@{
    ViewData["Title"] = "Company-Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company</h4>
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AutomateFulfillment)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AutomateFulfillment)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ShippoAPIKey)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ShippoAPIKey)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IncludePackingSlipOnLabel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IncludePackingSlipOnLabel)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyGUID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CompanyGUID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DefaultFulfillmentMethod)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DefaultFulfillmentMethod)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DefaultFulfillmentStrategy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DefaultFulfillmentStrategy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DefaultAllocationStrategy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DefaultAllocationStrategy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedOn)
        </dd>

    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="CompanyID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InventoryStudio/InventoryStudio/Views/Company/Details.cshtml
@model Company

@{
    ViewData["Title"] = "Company-Details";

    string NormalizedBoolean(bool value)
    {
        return value ? "Yes" : "No";
    }
}

<div class="container-fluid py-4">
    <div class="card custom-card">
        <div class="card-header hstack justify-content-between align-items-center">
            <div class="card-title">Company Details</div>
            <div class="hstack btn-list mt-md-0 mt-2">
                <a asp-controller="Company" asp-action="Edit" asp-route-id="@Model.CompanyID" type="button" class="btn btn-sm btn-primary btn-wave hstack align-items-center" aria-label="Edit company button">
                    <i class="bi-pencil-fill me-2 align-middle d-inline-block fs-16"></i>Edit Company
                </a>
                <a asp-controller="Company" asp-action="Index" type="button" class="btn btn-sm btn-light btn-wave hstack align-items-center" aria-label="back to list button">
                    Back to List
                </a>
            </div>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.CompanyName)</label>
                    <p>@Model.CompanyName</p>
                </div>

                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.AutomateFulfillment)</label>
                    <p>@NormalizedBoolean(Model.AutomateFulfillment)</p>
                </div>

                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.ShippoAPIKey)</label>
                    <p>@Model.ShippoAPIKey</p>
                </div>

                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.IncludePackingSlipOnLabel)</label>
                    <p>@NormalizedBoolean(Model.IncludePackingSlipOnLabel)</p>
                </div>

                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.CompanyGUID)</label>
                    <p>@Model.CompanyGUID</p>
                </div>

                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.DefaultAllocationStrategy)</label>
                    <p>@Model.DefaultFulfillmentMethod</p>
                </div>

                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.DefaultFulfillmentStrategy)</label>
                    <p>@Model.DefaultFulfillmentStrategy</p>
                </div>

                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.DefaultAllocationStrategy)</label>
                    <p>@Model.DefaultAllocationStrategy</p>
                </div>

                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.CreatedOn)</label>
                    <p>@Model.CreatedOn</p>
                </div>

                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.CreatedBy)</label>
                    <p>@Model.CreatedBy</p>
                </div>
            </div>
        </div>
    </div>
</div>

InventoryStudio/InventoryStudio/Views/Company/Edit.cshtml
@model InventoryStudio.Models.Company.EditCompanyViewModel

@{
    ViewData["Title"] = "Company Edit";
}

<div class="container-fluid py-4">
    <div class="card custom-card">
        <div class="card-header hstack justify-content-between align-items-center">
            <div class="card-title">Edit Company</div>
            <a asp-controller="Company" asp-action="Index" class="btn btn-sm btn-light">Back to List</a>
        </div>
        <div class="card-body">
            <form class="row" asp-controller="Company" asp-action="Edit" asp-route-id="@Model.CompanyID">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="CompanyID"/>
                <div class="form-group col-md-6 mb-3">
                    <label asp-for="CompanyName" class="form-label"></label>
                    <input asp-for="CompanyName" class="form-control"/>
                    <span asp-validation-for="CompanyName" class="text-danger"></span>
                </div>

                <div class="form-group col-md-6 mb-3">
                    <label asp-for="ShippoAPIKey" class="form-label"></label>
                    <input asp-for="ShippoAPIKey" class="form-control"/>
                    <span asp-validation-for="ShippoAPIKey" class="text-danger"></span>
                </div>

                <div class="form-group col-md-6 mb-3">
                    <label asp-for="DefaultFulfillmentMethod" class="form-label"></label>
                    <input asp-for="DefaultFulfillmentMethod" class="form-control"/>
                    <span asp-validation-for="DefaultFulfillmentMethod" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6 mb-3">
                    <label asp-for="DefaultFulfillmentStrategy" class="form-label"></label>
                    <input asp-for="DefaultFulfillmentStrategy" class="form-control"/>
                    <span asp-validation-for="DefaultFulfillmentStrategy" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6 mb-3">
                    <label asp-for="DefaultAllocationStrategy" class="form-label"></label>
                    <input asp-for="DefaultAllocationStrategy" class="form-control"/>
                    <span asp-validation-for="DefaultAllocationStrategy" class="text-danger"></span>
                </div>
                <div class="form-group form-check col-md-12 mb-3 ms-3">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="AutomateFulfillment"/> @Html.DisplayNameFor(model => model.AutomateFulfillment)
                    </label>
                </div>
                <div class="form-group form-check col-md-12 mb-3 ms-3">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="IncludePackingSlipOnLabel"/> @Html.DisplayNameFor(model => model.IncludePackingSlipOnLabel)
                    </label>
                </div>
                <div class="form-group col-md-12">
                    <input type="submit" value="Save" class="btn btn-primary"/>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

InventoryStudio/InventoryStudio/Views/Company/Index.cshtml
@model List<Company>

@{
    ViewData["Title"] = "Company";
    var normalizeBoolean = "normalizedBooleanFn";
}


<div class="container-fluid py-4 h-100">
    <div class="card custom-card h-100">
        <div class="card-header hstack align-items-center justify-content-between">
            <div class="card-title">
                Company Management
            </div>
            <div class="hstack btn-list mt-md-0 mt-2">
                <a asp-controller="Company" asp-action="Create" type="button" class="btn btn-sm btn-primary btn-wave hstack align-items-center" aria-label="Create company button">
                    <i class="bi-plus me-2 align-middle d-inline-block fs-16"></i>Create Company
                </a>
            </div>
        </div>
        <div class="card-body">
            <ejs-grid id="Grid" class="h-100" allowPaging="true" allowReordering="true" allowSorting="true" toolbarClick="toolbarClick" allowSelection="true" allowFiltering="true" enableStickyHeader="true" width="100%" height="100%"
                      allowExcelExport="true" allowPdfExport="true" toolbar="@(new List<string>() { "Delete", "PdfExport", "ExcelExport" })">

                <e-grid-editSettings showDeleteConfirmDialog="true" allowDeleting="true">
                </e-grid-editSettings>
                <e-grid-filterSettings type="Excel" mode="OnEnter"></e-grid-filterSettings>
                <e-data-manager url="/Company/UrlDatasource" adaptor="UrlAdaptor" insertUrl="/Company/Insert"
                                updateUrl="/Company/Update" removeUrl="/Company/Remove">
                </e-data-manager>
                @* <e-grid-pagesettings pageCount="5"></e-grid-pagesettings> *@
                <e-grid-columns>
                    <e-grid-column visible="false" field="CompanyID" headerText="ID" type="int" isPrimaryKey="true"
                                   validationRules="@(new { number = true })" width="80">
                    </e-grid-column>
                    <e-grid-column field="CompanyName" headerText="Company Name" width="120"></e-grid-column>
                    <e-grid-column field="AutomateFulfillment" headerText="Automate Fulfillment" valueAccessor="normalizeBoolean" width="120"></e-grid-column>
                    <e-grid-column field="ShippoAPIKey" headerText="Shippo API Key" width="120"></e-grid-column>
                    <e-grid-column field="IncludePackingSlipOnLabel" headerText="Include Packing Slip" valueAccessor="normalizeBoolean" width="120"></e-grid-column>
                    <e-grid-column field="DefaultFulfillmentMethod" headerText="Default Fulfillment Method" width="120"></e-grid-column>
                    <e-grid-column field="DefaultFulfillmentStrategy" headerText="Default Fulfillment Strategy" width="120"></e-grid-column>
                    <e-grid-column field="DefaultAllocationStrategy" headerText="Default Allocation Strategy" width="120"></e-grid-column>
                    <e-grid-column headerText="Actions" template="#actions" width="100" maxWidth="100"></e-grid-column>
                </e-grid-columns>
            </ejs-grid>
        </div>
    </div>
</div>

<!-- Actions template -->
<script id="actions" type="text/x-template">
    <div class="hstack gap-2">
        <a href="/Company/Edit?id=${CompanyID}" class="btn btn-icon btn-warning-light" data-bs-toggle="tooltip" title="Edit user" aria-label="Edit user button">
            <i class="bi-pencil-fill"></i>
        </a>
        <a href="/Company/Details?id=${CompanyID}" class="btn btn-icon btn-info-light" data-bs-toggle="tooltip" title="View user" aria-label="View user button">
            <i class="bi-eye-fill"></i>
        </a>
    </div>
</script>

<script src="@Url.Content("~/js/utils/utils.js")"></script>

<!-- Javascript logic for datagrid -->
<script lang="js">
    var normalizedBooleanFn = normalizedBoolean;
    const toolbarClick = customExportToolbarClick("Grid", "IS_Companies");
</script>