InventoryStudio/InventoryStudio/Models/Inventory/AdjustmentViewModel.cs
using System.ComponentModel;
using ISLibrary;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace InventoryStudio.Models
{
    public class AdjustmentViewModel
    {
        public string Memo { get; set; }
        public string LocationID { get; set; }

        [ValidateNever]
        public List<AdjustmentLine> AdjustmentLines { get; set; }
       
    }
}

InventoryStudio/InventoryStudio/Models/Inventory/ItemUnitViewModel.cs
using System.ComponentModel;
using ISLibrary;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace InventoryStudio.Models
{
    public class ItemUnitViewModel
    {
        public string Name { get; set; }

        [ValidateNever]
        public List<ItemUnit> ItemUnits { get; set; }
       
    }
}

InventoryStudio/InventoryStudio/Controllers/Inventory/AdjustmentController.cs
using InventoryStudio.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ISLibrary;
using System.Security.Claims;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Syncfusion.EJ2.Base;
using Newtonsoft.Json;

namespace InventoryStudio.Controllers
{
    public class AdjustmentController : BaseController

    { 
        private readonly UserManager<User> _userManager;
        private readonly IAuthorizationService _authorizationService;

        public AdjustmentController(UserManager<User> userManager, IAuthorizationService authorizationService)
        {
            _userManager = userManager;
            _authorizationService = authorizationService;
        }

        [Authorize(Policy = "Inventory-Adjustment-List")]
        public async Task<IActionResult> IndexAsync()
        {
            var organizationClaim = User.Claims.FirstOrDefault(c => c.Type == "CompanyId");
            if (organizationClaim != null)
            {
                //use ViewBag to control Button show/hide
                var permissions = new Dictionary<string, bool>
                {
                    ["CanCreate"] = (await _authorizationService.AuthorizeAsync(User, "Inventory-Adjustment-Create")).Succeeded,
                    ["CanView"] = (await _authorizationService.AuthorizeAsync(User, "Inventory-Adjustment-View")).Succeeded,
                    ["CanDelete"] = (await _authorizationService.AuthorizeAsync(User, "Item-Item-Delete")).Succeeded,
                };
                ViewBag.Permissions = permissions;


                return View("~/Views/Inventory/Adjustment/Index.cshtml");
            }

            ViewBag.ErrorMessage = "Please create or Choose Comapny";


            return View("Error");
        }


        [Authorize(Policy = "Inventory-Adjustment-Create")]
        public IActionResult Create()
        {
            return View("~/Views/Inventory/Adjustment/Create.cshtml");
        }

        [Authorize(Policy = "Inventory-Adjustment-Create")]
        [HttpPost]
        public IActionResult Create(AdjustmentViewModel adjustmentViewModel)
        {
            var organizationClaim = User.Claims.FirstOrDefault(c => c.Type == "CompanyId");
            if (organizationClaim == null)
            {
                ModelState.AddModelError("", "Invalid organization information.");
                return View("~/Views/Inventory/Adjustment/Create.cshtml", adjustmentViewModel);
            }

            Adjustment objAdjustment = new Adjustment();
            objAdjustment.CreatedBy = Convert.ToString(_userManager.GetUserId(User));
            objAdjustment.CompanyID = organizationClaim.Value;
            objAdjustment.Memo = adjustmentViewModel.Memo;
            objAdjustment.LocationID = adjustmentViewModel.LocationID;
            objAdjustment.AdjustmentLines = adjustmentViewModel.AdjustmentLines;
            try
            {
                objAdjustment.Create();
                return RedirectToAction("Details", new { id = objAdjustment.AdjustmentID });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("created_error", ex.Message);
                return View("~/Views/Inventory/Adjustment/Create.cshtml", adjustmentViewModel);
            }
        }            


        public IActionResult Details(string? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var organizationClaim = User.Claims.FirstOrDefault(c => c.Type == "CompanyId");
            var objAdjustment = new Adjustment(id);

            if (objAdjustment == null)
            {
                return NotFound();
            }

            if (objAdjustment.CompanyID != organizationClaim.Value)
            {
                TempData["ErrorMessage"] = "You don't have permission to change other company's data.";
                return RedirectToAction("Index");
            }

            var itemDetailsViewModel = new AdjustmentViewModel();

            itemDetailsViewModel.Memo = objAdjustment.Memo;
            itemDetailsViewModel.LocationID = objAdjustment.LocationID;
            itemDetailsViewModel.AdjustmentLines = objAdjustment.AdjustmentLines;

            return View("~/Views/Inventory/Adjustment/Details.cshtml", itemDetailsViewModel);
        }

        public IActionResult UrlDataSource([FromBody] DataManagerRequest dm)
        {
            IEnumerable<Adjustment> dataSource = new List<Adjustment>().AsEnumerable();
            DataOperations operation = new();
            int totalRecord = 0;
            if (dm.Skip != 0 || dm.Take != 0)
            {
                Claim? company = User.Claims.FirstOrDefault(t => t.Type == "CompanyId");
                if (company != null)
                {
                    AdjustmentFilter AdjustmentFilter = new AdjustmentFilter();

                    dataSource = Adjustment.GetAdjustments(
                        company.Value,
                        AdjustmentFilter,
                        dm.Take,
                        (dm.Skip / dm.Take) + 1,
                        out totalRecord
                    ).AsEnumerable();
                }
            }

            if (dm.Search != null && dm.Search.Count > 0)
            {
                dataSource = operation.PerformSearching(dataSource, dm.Search); //Search
            }

            if (dm.Sorted != null && dm.Sorted.Count > 0) //Sorting
            {
                dataSource = operation.PerformSorting(dataSource, dm.Sorted);
            }

            if (dm.Where != null && dm.Where.Count > 0) //Filtering
            {
                if (dm.Where != null && dm.Where.Any()) //Filtering
                {
                    foreach (WhereFilter whereFilter in dm.Where)
                    {
                        if (whereFilter.IsComplex)
                        {
                            foreach (WhereFilter whereFilterPredicate in whereFilter.predicates)
                            {
                                dataSource = operation.PerformFiltering(
                                    dataSource,
                                    dm.Where,
                                    whereFilterPredicate.Operator
                                );
                            }
                        }
                        else
                        {
                            dataSource = operation.PerformFiltering(
                                dataSource,
                                dm.Where,
                                dm.Where.First().Operator
                            );
                        }
                    }
                }
            }

            if (dm.Skip != 0)
            {
                dataSource = operation.PerformSkip(dataSource, dm.Skip); //Paging
            }

            if (dm.Take != 0)
            {
                dataSource = operation.PerformTake(dataSource, dm.Take);
            }

            JsonSerializerOptions jsonSerializerOptions = new() { PropertyNamingPolicy = null };
            return dm.RequiresCounts
                ? Json(new { result = dataSource, count = totalRecord }, jsonSerializerOptions)
                : Json(dataSource, jsonSerializerOptions);
        }


     
    }
}

InventoryStudio/InventoryStudio/Controllers/Inventory/BinController.cs
using InventoryStudio.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ISLibrary;
using System.Security.Claims;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Syncfusion.EJ2.Base;
using Newtonsoft.Json;
using NPOI.POIFS.NIO;

namespace InventoryStudio.Controllers
{
    public class BinController : BaseController

    { 
        private readonly UserManager<User> _userManager;
        private readonly IAuthorizationService _authorizationService;

        public BinController(UserManager<User> userManager, IAuthorizationService authorizationService)
        {
            _userManager = userManager;
            _authorizationService = authorizationService;
        }
  
        [Authorize(Policy = "Inventory-Bin-Create")]
        [HttpPost]
        public IActionResult Create(Bin bin)
        {
            var organizationClaim = User.Claims.FirstOrDefault(c => c.Type == "CompanyId");
            if (organizationClaim == null)
            {
                return Json(new { error = "Invalid organization information." });
            }

            Bin objBin = new Bin();
            bin.CreatedBy = Convert.ToString(_userManager.GetUserId(User));
            bin.CompanyID = organizationClaim.Value;
            try
            {
                bin.Create();
                return Json(new { succcess = "Create Successed" });
            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message });
            }
        }


        [Authorize(Policy = "Inventory-Bin-Delete")]
        public IActionResult Delete(string BinID)
        {           
            var organizationClaim = User.Claims.FirstOrDefault(c => c.Type == "CompanyId");
            var objBin = new Bin(organizationClaim.Value,BinID);

            if (objBin == null)
            {
                return Json(new { error = "Not Found" });
            }

            try
            {
                objBin.Delete();
                return Json(new { succcess = "Delete Successed" });
            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message });
            }
           
        
        }

    }
}

InventoryStudio/InventoryStudio/Controllers/Inventory/ItemUnitController.cs
using InventoryStudio.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ISLibrary;
using System.Security.Claims;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Syncfusion.EJ2.Base;
using Newtonsoft.Json;

namespace InventoryStudio.Controllers
{
    public class ItemUnitController : BaseController

    { 
        private readonly UserManager<User> _userManager;
        private readonly IAuthorizationService _authorizationService;

        public ItemUnitController(UserManager<User> userManager, IAuthorizationService authorizationService)
        {
            _userManager = userManager;
            _authorizationService = authorizationService;
        }

        [Authorize(Policy = "Inventory-ItemUnit-List")]
        public async Task<IActionResult> IndexAsync()
        {
            var organizationClaim = User.Claims.FirstOrDefault(c => c.Type == "CompanyId");
            if (organizationClaim != null)
            {
                //use ViewBag to control Button show/hide
                var permissions = new Dictionary<string, bool>
                {
                    ["CanCreate"] = (await _authorizationService.AuthorizeAsync(User, "Inventory-ItemUnit-Create")).Succeeded,
                    ["CanView"] = (await _authorizationService.AuthorizeAsync(User, "Inventory-ItemUnit-View")).Succeeded,
                    ["CanDelete"] = (await _authorizationService.AuthorizeAsync(User, "Item-ItemUnit-Delete")).Succeeded,
                };
                ViewBag.Permissions = permissions;


                return View("~/Views/Inventory/ItemUnit/Index.cshtml");
            }

            ViewBag.ErrorMessage = "Please create or Choose Comapny";


            return View("Error");
        }


        [Authorize(Policy = "Inventory-ItemUnit-Create")]
        public IActionResult Create()
        {
            return View("~/Views/Inventory/ItemUnit/Create.cshtml");
        }

        [Authorize(Policy = "Inventory-ItemUnit-Create")]
        [HttpPost]
        public IActionResult Create(ItemUnitViewModel itemUnitViewModel)
        {
            var organizationClaim = User.Claims.FirstOrDefault(c => c.Type == "CompanyId");
            if (organizationClaim == null)
            {
                ModelState.AddModelError("", "Invalid organization information.");
                return View("~/Views/Inventory/ItemUnit/Create.cshtml", itemUnitViewModel);
            }

            ItemUnitType objItemUnitType = new ItemUnitType();
            objItemUnitType.CreatedBy = Convert.ToString(_userManager.GetUserId(User));
            objItemUnitType.CompanyID = organizationClaim.Value;
            objItemUnitType.Name = itemUnitViewModel.Name;
            objItemUnitType.ItemUnits = itemUnitViewModel.ItemUnits;
            try
            {
                objItemUnitType.Create();
                return RedirectToAction("Details", new { id = objItemUnitType.ItemUnitTypeID });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("created_error", ex.Message);
                return View("~/Views/Inventory/ItemUnit/Create.cshtml", itemUnitViewModel);
            }
        }            


        public IActionResult Details(string? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var organizationClaim = User.Claims.FirstOrDefault(c => c.Type == "CompanyId");
            var objItemUnitType = new ItemUnitType(id);

            if (objItemUnitType == null)
            {
                return NotFound();
            }

            if (objItemUnitType.CompanyID != organizationClaim.Value)
            {
                TempData["ErrorMessage"] = "You don't have permission to change other company's data.";
                return RedirectToAction("Index");
            }

            var itemUnitViewModel = new ItemUnitViewModel();

            itemUnitViewModel.Name = objItemUnitType.Name;
            itemUnitViewModel.ItemUnits = objItemUnitType.ItemUnits;

            return View("~/Views/Inventory/ItemUnit/Details.cshtml", itemUnitViewModel);
        }

        public IActionResult UrlDataSource([FromBody] DataManagerRequest dm)
        {
            IEnumerable<ItemUnitType> dataSource = new List<ItemUnitType>().AsEnumerable();
            DataOperations operation = new();
            int totalRecord = 0;
            if (dm.Skip != 0 || dm.Take != 0)
            {
                Claim? company = User.Claims.FirstOrDefault(t => t.Type == "CompanyId");
                if (company != null)
                {
                    ItemUnitTypeFilter ItemUnitTypeFilter = new ItemUnitTypeFilter();

                    dataSource = ItemUnitType.GetItemUnitTypes(
                        company.Value,
                        ItemUnitTypeFilter,
                        dm.Take,
                        (dm.Skip / dm.Take) + 1,
                        out totalRecord
                    ).AsEnumerable();
                }
            }

            if (dm.Search != null && dm.Search.Count > 0)
            {
                dataSource = operation.PerformSearching(dataSource, dm.Search); //Search
            }

            if (dm.Sorted != null && dm.Sorted.Count > 0) //Sorting
            {
                dataSource = operation.PerformSorting(dataSource, dm.Sorted);
            }

            if (dm.Where != null && dm.Where.Count > 0) //Filtering
            {
                if (dm.Where != null && dm.Where.Any()) //Filtering
                {
                    foreach (WhereFilter whereFilter in dm.Where)
                    {
                        if (whereFilter.IsComplex)
                        {
                            foreach (WhereFilter whereFilterPredicate in whereFilter.predicates)
                            {
                                dataSource = operation.PerformFiltering(
                                    dataSource,
                                    dm.Where,
                                    whereFilterPredicate.Operator
                                );
                            }
                        }
                        else
                        {
                            dataSource = operation.PerformFiltering(
                                dataSource,
                                dm.Where,
                                dm.Where.First().Operator
                            );
                        }
                    }
                }
            }

            if (dm.Skip != 0)
            {
                dataSource = operation.PerformSkip(dataSource, dm.Skip); //Paging
            }

            if (dm.Take != 0)
            {
                dataSource = operation.PerformTake(dataSource, dm.Take);
            }

            JsonSerializerOptions jsonSerializerOptions = new() { PropertyNamingPolicy = null };
            return dm.RequiresCounts
                ? Json(new { result = dataSource, count = totalRecord }, jsonSerializerOptions)
                : Json(dataSource, jsonSerializerOptions);
        }


     
    }
}

InventoryStudio/InventoryStudio/Views/Inventory/Location/Details.cshtml
@model LocationViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="container-fluid py-4">
    <div class="card custom-card">
        <div class="card-header hstack justify-content-between align-items-center">
            <div class="card-title">Location Details</div>
            <div class="hstack btn-list mt-md-0 mt-2">
                <a asp-controller="Location" asp-action="Edit" asp-route-id="@Model.LocationID" type="button" class="btn btn-sm btn-primary btn-wave hstack align-items-center" aria-label="Edit Address button">
                    <i class="bi-pencil-fill me-2 align-middle d-inline-block fs-16"></i>Edit Location
                </a>
                <a class="btn btn-sm btn-light" asp-controller="Location" asp-action="Index" aria-label="Back to List">Back to List</a>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.ParentLocationID)</label>
                    <p>@Model.ParentLocationID</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.LocationNumber)</label>
                    <p>@Model.LocationNumber</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.LocationName)</label>
                    <p>@Model.LocationName</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.UseBins)</label>
                    <p>@Model.UseBins</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.UseLotNumber)</label>
                    <p>@Model.UseLotNumber</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.UseCartonNumber)</label>
                    <p>@Model.UseCartonNumber</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.UseVendorCartonNumber)</label>
                    <p>@Model.UseVendorCartonNumber</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.UseSerialNumber)</label>
                    <p>@Model.UseSerialNumber</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.AllowMultiplePackagePerFulfillment)</label>
                    <p>@Model.AllowMultiplePackagePerFulfillment</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.AllowAutoPick)</label>
                    <p>@Model.AllowAutoPick</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.AllowAutoPickApproval)</label>
                    <p>@Model.AllowAutoPickApproval</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.AllowNegativeInventory)</label>
                    <p>@Model.AllowNegativeInventory</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.DefaultAddressValidation)</label>
                    <p>@Model.DefaultAddressValidation</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.DefaultSignatureRequirement)</label>
                    <p>@Model.DefaultSignatureRequirement</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.DefaultSignatureRequirementAmount)</label>
                    <p>@Model.DefaultSignatureRequirementAmount</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.DefaultCountryOfOrigin)</label>
                    <p>@Model.DefaultCountryOfOrigin</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.DefaultHSCode)</label>
                    <p>@Model.DefaultHSCode</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.DefaultLowestShippingRate)</label>
                    <p>@Model.DefaultLowestShippingRate</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.MaximumPackScanRequirement)</label>
                    <p>@Model.MaximumPackScanRequirement</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.MaximumPickScanRequirement)</label>
                    <p>@Model.MaximumPickScanRequirement</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.DisplayWeightMode)</label>
                    <p>@Model.DisplayWeightMode</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.FulfillmentCombineStatus)</label>
                    <p>@Model.FulfillmentCombineStatus</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.EnableSimpleMode)</label>
                    <p>@Model.EnableSimpleMode</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.EnableSimpleModePack)</label>
                    <p>@Model.EnableSimpleModePack</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.EnableSimpleModePick)</label>
                    <p>@Model.EnableSimpleModePick</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.ValidateSource)</label>
                    <p>@Model.ValidateSource</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.VarianceBinID)</label>
                    <p>@Model.VarianceBinID</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.Address)</label>
                    <p>@Model.Address</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.Company)</label>
                    <p>@Model.Company</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.DefaultPackageDimension)</label>
                    <p>@Model.DefaultPackageDimension</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.CreatedBy)</label>
                    <p>@Model.CreatedBy</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.CreatedOn)</label>
                    <p>@Model.CreatedOn</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.UpdatedBy)</label>
                    <p>@Model.UpdatedBy</p>
                </div>
                <div class="d-flex flex-column col-md-4">
                    <label class="form-label">@Html.DisplayNameFor(model => model.UpdatedOn)</label>
                    <p>@Model.UpdatedOn</p>
                </div>
            </div>

            <div class="row">
                <table class="table" id="itemKitTable">
                    <thead>
                        <tr>
                            <th>Action</th>
                            <th>Bin Number</th>
                            <th>
                                Locked
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var Bin in Model.BinList)
                        {
                            <tr>
                                <td>
                                    <form asp-controller="Bin" asp-action="Delete" method="post" onsubmit="return confirm('Are you sure you want to delete this bin?')">
                                        <input type="hidden" name="BinID" value="@Bin.BinID" />
                                        <button type="submit" class="btn btn-link">Delete</button>
                                    </form>
                                    
                                </td>
                                <td>
                                    @Bin.BinNumber

                                </td>
                                <td>
                                    @Bin.IsLocked
                                </td>                               
                            </tr>
                        }
                         <form asp-controller="Bin" asp-action="Create"  method="post" >
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label>BinNumber</label>
                                    <input name="BinNumber" class="form-control" />
                                </div>
                                <div class="form-group col-md-6">
                                    <label>IsLocked</label>
                                    <input name="IsLocked" class="form-control" />
                                </div>

                                <input type="hidden" asp-for="LocationID" />

                            </div>
                            <button type="submit" class="btn btn-success">Save</button>

                           

                         </form>

                    </tbody>
                </table>
            </div>

            <div class="row">
                @await Html.PartialAsync("~/Views/System/AuditData/_Index.cshtml", Model.AuditDataList)
            </div>
        </div>
    </div>
</div>